project_name: envsnap
snapshot:
  name_template: '{{ .Tag }}-next'
checksum:
  name_template: '{{ .ProjectName }}-checksums-{{ .Tag }}.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
release:
  github:
    owner: edaniszewski
    name: envsnap
  draft: false
  prerelease: auto
  name_template: '{{ .Version }}'
before:
  hooks:
    - go mod download
builds:
  -
    main: ./cmd/envsnap.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w
      - -X github.com/edaniszewski/envsnap/pkg.BuildDate={{ .Date }}
      - -X github.com/edaniszewski/envsnap/pkg.Commit={{ .ShortCommit }}
      - -X github.com/edaniszewski/envsnap/pkg.Tag={{ .Tag }}
      - -X github.com/edaniszewski/envsnap/pkg.GoVersion={{ .Env.GIMME_GO_VERSION }}
      - -X github.com/edaniszewski/envsnap/pkg.Version={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
      - envsnap
    image_templates:
      - 'edaniszewski/envsnap:{{ .Tag }}'
      - 'edaniszewski/envsnap:{{ .Major }}'
      - 'edaniszewski/envsnap:{{ .Major }}.{{ .Minor }}'
      - 'edaniszewski/envsnap:latest'
    build_flag_templates:
      - '--label=org.label-schema.version={{ .Version }}'
      - '--label=org.label-schema.build-date={{ .Date }}'
      - '--label=org.label-schema.vcs-ref={{ .ShortCommit }}'
archives:
  -
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: darwin
      linix: linux
brews:
  -
    github:
      owner: edaniszewski
      name: homebrew-tap
    commit_author:
      name: edaniszewski
      email: 'edaniszewski@gmail.com'
    homepage: 'https://github.com/edaniszewski/envsnap'
    description: 'Project-defined user environment snapshots for debugging and reporting'
    test: |
      system "#{bin}/envsnap --version"
