
builds:
  - env:
      - CGO_ENABLED = 0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
dockers:
  - image_templates:
      - ''
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: darwin
      linix: linux