dist: xenial
language: go
go:
  - '1.13.x'
services:
  - docker
install:
  - GO111MODULE=off go get -u golang.org/x/lint/golint
script:
  - make lint
  - make build
  - make test
  - curl -sL https://git.io/goreleaser | bash -s -- --debug --snapshot --rm-dist
after_success:
  - rm -rf dist/
  - test -z "$(git status --porcelain)"
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash -s -- --debug --rm-dist
    on:
      tags: true
notifications:
  email: false
